baseURL = 'https://AgileMissingManual.com/'
languageCode = 'en-us'
title = 'Agile Missing Manual'

googleAnalytics = "G-YLW402WWZF"

[module]
[[module.imports]]
  path = 'github.com/alex-shpak/hugo-book'

[params]
  # (Optional, default docs) Specify section of content to render as menu
  # You can also set value to "*" to render all sections to menu
  BookSection = '*'

  # Controls the default table of contents visibility on right side of pages.
  BookToC = false

defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true

# Needed for mermaid/katex shortcodes
[markup]
[markup.goldmark.renderer]
  unsafe = true

[languages]
  [languages.en]
    contentDir = 'content.en'
    languageName = 'English'
    weight = 1
